name: CI
on: workflow_dispatch

jobs:
  testing-ubuntu_latest-py3.6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup Python-3.6
        uses: actions/setup-python@v4
        with:
          python-version: 3.6
      - name: Perform test
        shell: bash
        run: |
          pip install .
          pip install pytest pillow
          python -m pytest .
